repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: 'https://github.com/ambv/black'
    rev: 23.1.0
    hooks:
      - id: black
        name: code formatter # default line length is 88
        language: python
        language_version: python3.11
        args:
          - '--include=''\.py?$'''
  - repo: 'https://github.com/pycqa/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - '--max-line-length=88'
          - '--ignore=E203,E722,F401,F841,W503'
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix
